name: Cache Node modules

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Yarn CLI
      # You may pin to the exact commit or the version.
      # uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8
      uses: CultureHQ/actions-yarn@v1.0.1
    - uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
    - run: yarn
    - run: echo "Yarn done"
